version: '3.8'

services:
  tiktok-downloader-api:
    build: 
      context: ./api
    container_name: tiktok-downloader-api
    ports:
      - "8006:8006"
    volumes:
      - ./logs:/app/logs
      - ./temp_videos:/app/temp_videos
    environment:
      - API_KEY=${API_KEY}
      - LOG_LEVEL=DEBUG
      - MAX_WORKERS=4  
    restart: unless-stopped