version: '3.8'

services:
  tiktok-api:
    build: 
      context: ./api
    ports:
      - "8006:8006"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./temp_videos:/app/temp_videos
    restart: unless-stopped